apiVersion: v1
kind: Service
metadata:
  name: hello-server
  namespace: default
  annotations:
    # Provisions an internet-facing NLB (faster and cheaper than Classic ELB)
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  type: LoadBalancer
  selector:
    app: hello-server
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
