apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: apps
  source:
    # Same repo, different path — your fork of this lab.
    # The path points at apps/hello-world/ which contains raw K8s manifests.
    repoURL: REPO_URL_PLACEHOLDER
    targetRevision: main
    path: apps/hello-world
  destination:
    server: https://kubernetes.default.svc
    namespace: hello
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
